// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts` (hash: da27791a91075c9f998765f68524113b)
// Runtime types generated with workerd@1.20250320.0 2024-09-26 nodejs_compat
declare namespace Cloudflare {
  interface Env {
    NEXTJS_ENV: string;
    DB: D1Database;
  }
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface CloudflareEnv extends Cloudflare.Env {}
